//==================================================
//     Outputs that match the input variables
//==================================================
output "dynamic_depends_on" {
  description = "The value of the `dynamic_depends_on` input variable."
  value       = var.dynamic_depends_on
}
output "filename" {
  description = "The value of the `filename` input variable."
  value       = var.filename
}
output "content" {
  description = "The value of the `content` input variable."
  value       = var.content
}
output "content_base64" {
  description = "The value of the `content_base64` input variable."
  value       = var.content_base64
}
output "file_permission" {
  description = "The value of the `file_permission` input variable, or the default value if the input was `null`."
  value       = var.file_permission
}
output "directory_permission" {
  description = "The value of the `directory_permission` input variable, or the default value if the input was `null`."
  value       = var.directory_permission
}
output "force_wait_for_apply" {
  description = "The value of the `force_wait_for_apply` input variable, or the default value if the input was `null`."
  value       = var.force_wait_for_apply
}
output "append" {
  description = "The value of the `append` input variable, or the default value if the input was `null`."
  value       = var.append
}
output "max_characters" {
  description = "The value of the `max_characters` input variable."
  value       = var.max_characters
}
output "force_update_last_modified" {
  description = "The value of the `force_update_last_modified` input variable, or the default value if the input was `null`."
  value       = var.force_update_last_modified
}
output "chunk_size" {
  description = "The value of the `chunk_size` input variable, or the default value if the input was `null`."
  value       = var.chunk_size
}
output "unix_interpreter" {
  description = "The value of the `unix_interpreter` input variable, or the default value if the input was `null`."
  value       = var.unix_interpreter
}
output "delete_after" {
  description = "The value of the `delete_after` input variable, or the default value if the input was `null`."
  value       = var.delete_after
}

//==================================================
//       Outputs generated by this module
//==================================================
locals {
  creation_done = jsonencode(data.external.create_file_chunk) != "" ? true : false
}

output "created" {
  description = "Always `true`, but does not return until the file has been created."
  value       = local.creation_done
}

output "complete" {
  description = "Always `true`, but does not return until the file has been created and, if desired, deleted as well."
  value       = length(var.delete_after) > 0 ? (jsonencode(data.external.delete_file[0]) == "" ? true : true) : local.creation_done
}

output "num_chunks" {
  description = "The number of chunks that the file was split into during the writing process (this output is only useful for debugging)."
  value       = local.num_chunks
}

output "modified" {
  description = "Whether the file had been (or, if the file can't be created until apply-time, will be) modified. Will be `true` if the file doesn't already exist or if the contents have changed, and `false` otherwise."
  value       = local.needs_creation
}
